/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class zy_myndk_JniUtil */

#ifndef _Included_zy_myndk_JniUtil
#define _Included_zy_myndk_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     zy_myndk_JniUtil
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_zy_myndk_JniUtil_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
